theme = { accent-color = "red" }

title = "TOML Config Example"

sidebar = [
  { text = "Getting Started", link = "/" },
  { text = "Migration Guide", link = "/migration-guide" }
]

[[top-nav]]
text = "Home"
link = "/"