name: Main
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
   runs-on: ubuntu-latest
   name: Build and Push
   steps:
    - name: git-checkout
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        npm install -g pnpm@9.1.0

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: 20

    - name: Install modules
      run: |
        pnpm install
    
    - name: Build
      run: pnpm build
      
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        GIT_CLONE_PROTECTION_ACTIVE: false
        BRANCH: build
        FOLDER: ./src
        MESSAGE: "Build: ({sha}) {msg}"